# Generated by Django 5.2.1 on 2025-05-27 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file", models.ImageField(upload_to="comfyui_output/")),
                ("title", models.CharField(max_length=200, verbose_name="이미지 제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("prompt", models.TextField(verbose_name="생성 프롬프트")),
                (
                    "style",
                    models.CharField(
                        max_length=100,
                        verbose_name="스타일 (예: cyberpunk, oriental, 3d)",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[("t2i", "Text-to-Image"), ("i2i", "Image-to-Image")],
                        default="t2i",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성 날짜"
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(default=0, verbose_name="좋아요 수"),
                ),
            ],
            options={
                "verbose_name": "생성 이미지",
                "verbose_name_plural": "생성 이미지들",
                "ordering": ["-created_at"],
            },
        ),
    ]
