# Generated by Django 5.2.1 on 2025-05-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_generator", "0003_conversation_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="source_type",
            field=models.CharField(
                choices=[("user", "사용자 생성"), ("admin", "관리자 업로드")],
                default="user",
                max_length=10,
                verbose_name="이미지 출처",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="summary",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="대화 요약"
            ),
        ),
    ]
