# Generated by Django 5.2.1 on 2025-05-29 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_generator", "0004_generatedimage_source_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="generatedimage",
            name="source_type",
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="is_showcase",
            field=models.BooleanField(default=False, verbose_name="갤러리 전시 여부"),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="타임스탬프"
            ),
        ),
    ]
