# Generated by Django 5.2.1 on 2025-05-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_generator", "0005_remove_conversation_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="summary",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="대화 요약"
            ),
        ),
    ]
