# Generated by Django 5.2.1 on 2025-05-30 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_generator", "0006_conversation_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="대화 시작 시간"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="image_file_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="이미지 파일 경로"
            ),
        ),
    ]
