# D:\\project3_test\\\\llm_cores\\\\positive_prompts.py

# 미리 정의된 긍정 프롬프트 카테고리 맵
# 각 키는 카테고리 이름이고, 값은 해당 카테고리에 적용될 긍정 프롬프트 문자열입니다.
POSITIVE_PROMPT_MAP = {
    "canny_effect": "sharp outlines, defined edges, clear contours, strong line art, detailed silhouette",
    "depth_effect": "three-dimensional, volumetric lighting, strong sense of depth, realistic perspective, detailed foreground and background, deep shadows, atmospheric perspective",
    "lineart_effect": "crisp line art, clean strokes, intricate details, precise linework, smooth lines, comic book style lines, graphic novel aesthetic",
    # [수정 부분] color_transfer_effect 프롬프트에 원본 색감 유지 강조
    "color_transfer_effect": "vibrant color palette, rich hues, harmonious colors, artistic color scheme, color grading, vivid and expressive colors, recolored, enhanced color saturation, maintaining original photo's color palette, based on original color scheme",
    "stylized_lighting": "cinematic lighting, dramatic shadows, soft ambient light, volumetric light, rim light, golden hour, studio lighting",
    "texture_detail": "intricate textures, detailed surfaces, realistic materials, fine details, subtle patterns",
    # [주석 처리 시작] realistic_detail은 사실주의 장르에 해당하여 다른 스타일과 충돌 가능성 있음
    # "realistic_detail": "hyperrealistic rendering, ultra high definition, photorealistic, lifelike details, naturalistic, fine-tuned realism",
    # [주석 처리 끝]
    "character_focus": "solo character, detailed facial features, expressive eyes, dynamic pose, full body shot, intricate costume details",
    "background_detail": "detailed background, immersive environment, rich scenery, complex backdrop, contextual setting",
    "normal_map_effect": "strong sense of form, defined geometry, sculptural quality, three-dimensional structure, precise surface details, realistic bumps and depressions, material definition, volumetric shapes, geometric accuracy",
    # [추가 부분] OpenPose ControlNet 사용 시 강조할 긍정 프롬프트
    # [수정 부분] openpose_focus 프롬프트에 자세 보존 강조 문구 추가
    "openpose_focus": "accurate human pose, clear body positioning, well-defined skeleton, precise limb articulation, natural hand gesture, detailed fingers, correct foot placement, dynamic full body, proper anatomical structure, no distorted limbs, realistic posture, **maintaining original pose, preserving original body language, pose transfer**",
    # [수정] 지브리 스타일 강조 프롬프트 디테일 강화
    "ghibli_style": "Studio Ghibli style, anime art style, hand-drawn animation, soft colors, dreamy atmosphere, painterly, whimsical, fantasy landscape, lush greenery, expressive characters, nostalgic, warm lighting, watercolor textures, **ethereal glow, gentle sunlight, detailed natural elements, flowing hair, expressive eyes, subtle emotions, sense of wonder, peaceful, harmonious, vibrant but soft palette, traditional cel animation feel, fantastical creatures, magical realism, intricate architecture, serene landscapes, fluffy clouds, sparkling water, rustling leaves, sense of adventure, childlike innocence, heartwarming, comforting, soft focus, depth of field, atmospheric perspective, beautiful skies, vibrant flora and fauna, detailed background elements, a touch of melancholy, a sense of hope, a journey, a hidden world**",

    # [추가 부분 시작] 새로운 장르 및 화가 스타일 프롬프트 (전통 회화)
    "history_painting_style": "history painting, epic narrative, grand composition, dramatic scene, moralistic themes",
    "portraiture_style": "portraiture, expressive portrait, detailed facial features, character study",
    "landscape_painting_style": "landscape painting, scenic view, natural beauty, atmospheric landscape, serene, vast",
    "still_life_painting_style": "still life painting, arranged objects, detailed textures, symbolic composition, classical setup",
    "genre_painting_style": "genre painting, everyday life scene, domestic setting, candid moment, social realism",

    # [추가 부분 시작] 새로운 장르 및 화가 스타일 프롬프트 (주요 예술 운동 및 스타일)
    "renaissance_style": "Renaissance art, classical composition, chiaroscuro, sfumato, idealized forms, religious themes, mythological scenes",
    "baroque_style": "Baroque painting, dramatic lighting, intense emotion, dynamic composition, rich colors, deep shadows, movement",
    "rococo_style": "Rococo art, delicate colors, playful scenes, elaborate ornamentation, curving lines, whimsical",
    "neoclassical_style": "Neoclassical art, classical antiquity, sharp contours, moralistic themes, balanced composition, heroic figures",
    "romanticism_style": "Romanticism art, emotional intensity, dramatic landscapes, sublime nature, exotic themes, personal expression",
    "realism_style": "Realism art, true-to-life depiction, unembellished reality, social commentary, gritty details",
    "impressionism_style": "Impressionist painting, broken brushstrokes, light effects, fleeting moments, vibrant colors, outdoor scenes",
    "post_impressionism_style": "Post-Impressionist art, expressive color, symbolic content, distinct brushwork",
    "symbolism_style": "Symbolism art, mystical, dreamlike, allegorical, hidden meanings, evocative",
    "art_nouveau_style": "Art Nouveau style, organic lines, flowing curves, decorative, natural motifs, elegant",
    "fauvism_style": "Fauvism, bold colors, expressive brushstrokes, simplified forms, vibrant hues, non-naturalistic color",
    "expressionism_style": "Expressionism, distorted forms, strong emotions, subjective reality, angst, raw, psychological",
    "cubism_style": "Cubism, fragmented forms, geometric shapes, multiple perspectives, abstract composition, analytical, synthetic",
    "futurism_style": "Futurism, dynamic motion, speed, technology, urban energy, fragmented forms, blur of movement",
    "constructivism_style": "Constructivism, geometric abstraction, industrial materials, functional forms, bold lines, graphic design",
    "suprematism_style": "Suprematism, pure geometric abstraction, fundamental forms, spiritual purity, minimalist",
    "dadaism_style": "Dadaism, absurd, anti-art, rebellious, collage, ready-made, nonsensical",
    "surrealism_style": "Surrealist art, dreamlike, bizarre, illogical, subconscious, fantastical, uncanny, **realistic rendering of impossible scenes, dreamlike yet tangible, photorealistic elements within fantastical context**", # 초현실주의 강화
    "abstract_expressionism_style": "Abstract Expressionism, spontaneous brushstrokes, non-representational, gestural, emotional intensity, large scale",
    "pop_art_style": "Pop Art, silkscreen, mass production, celebrity portraits, bright colors, iconic imagery, graphic, bright",
    "op_art_style": "Op Art, optical illusions, geometric patterns, vibrating effects, visual trickery, mesmerizing",
    "minimalism_style": "Minimalism, simplicity, essential forms, reductive, geometric, understated, clean",
    "conceptual_art_style": "Conceptual Art, idea-driven, thought-provoking, symbolic, abstract concepts, intellectual",
    "photorealism_style": "Photorealism, hyperrealistic, ultra high definition, lifelike details, photographic accuracy, **micro-details, subtle light interplay, accurate material rendering, crisp focus, intricate textures, realistic imperfections, naturalistic lighting, true-to-life colors, physically based rendering (PBR)**", # 포토리얼리즘 강화
    "street_art_style": "street art, graffiti, mural, urban art, bold lines, vibrant colors, stencil art, gritty, raw",
    "digital_art_style": "digital painting, digital illustration, smooth gradients, clean lines, crisp details, vibrant digital colors, high resolution",
    "nft_art_style": "NFT art, blockchain art, digital collectible, unique digital artwork, crypto art",

    # [추가 부분 시작] 새로운 장르 및 화가 스타일 프롬프트 (매체 기반 장르)
    "oil_painting_style": "oil painting, rich textures, deep colors, layered brushstrokes, impasto",
    "watercolor_style": "watercolor painting, soft washes, transparent colors, delicate strokes, ethereal",
    "acrylic_painting_style": "acrylic painting, vibrant colors, bold strokes, versatile medium, contemporary feel",
    "gouache_style": "gouache painting, opaque watercolor, matte finish, vibrant pigments, poster-like",
    "fresco_style": "fresco painting, mural art, classical technique, wall painting, ancient style",
    "drawing_style": "drawing, sketch, line art, pencil drawing, charcoal drawing, ink drawing, cross-hatching",
    "printmaking_style": "printmaking, etching, lithography, woodcut, screen print, linocut, graphic, bold lines",
    "collage_style": "collage art, mixed media, cut and paste, fragmented imagery, layered, textured",
    "pixel_art_style": "pixel art, retro gaming style, low resolution, blocky, nostalgic, 8-bit, 16-bit",
    "voxel_art_style": "voxel art, 3D pixel art, blocky 3D, cubic forms, Minecraft style",

    # [추가 부분 시작] 새로운 장르 및 화가 스타일 프롬프트 (주제/내용 기반 장르)
    "abstract_art_style": "abstract art, non-representational, pure forms, expressive abstraction, conceptual",
    "social_commentary_art_style": "social commentary art, protest art, critical perspective, thought-provoking, impactful",
    "eco_art_style": "eco art, environmental themes, nature-inspired, sustainable art, organic forms",
    "sci_art_style": "sci-art, scientific visualization, data art, biological art, futuristic concepts, intricate systems",
    "fantasy_art_style": "fantasy art, mythical creatures, magical realms, epic fantasy, whimsical, enchanted",
    "sci_fi_art_style": "sci-fi art, futuristic, cyberpunk, space opera, dystopian, technological, advanced",
    "comic_cartoon_style": "comic art, cartoon style, graphic novel, sequential art, bold lines, humorous, exaggerated",
    "illustration_style": "illustration, narrative art, visual storytelling, decorative art, book illustration",
    "fan_art_style": "fan art, character tribute, fictional universe, homage, stylized interpretation",

    # [추가 부분 시작] 화가별 스타일 프롬프트
    # 전통적인 회화 장르 화가
    "jacques_louis_david_style": "Jacques-Louis David style, neoclassical, heroic, dramatic, sharp contours, classical composition",
    "eugene_delacroix_style": "Eugène Delacroix style, romanticism, emotional, vibrant colors, dynamic composition, exotic themes",
    "leonardo_da_vinci_style": "Leonardo da Vinci style, Renaissance, sfumato, chiaroscuro, anatomical accuracy, expressive faces, soft transitions",
    "michelangelo_style": "Michelangelo style, Renaissance, powerful figures, sculptural forms, dramatic poses, heroic, monumental",
    "rembrandt_style": "Rembrandt style, Baroque, chiaroscuro, deep shadows, emotional depth, realistic portraits, warm tones",
    "francisco_goya_style": "Francisco Goya style, Romanticism, dark themes, expressive, social commentary, dramatic, unsettling",
    "john_singer_sargent_style": "John Singer Sargent style, elegant portraits, fluid brushwork, vibrant colors, high society, graceful",
    "vincent_van_gogh_style": "Vincent van Gogh style, Post-Impressionism, bold brushstrokes, vibrant colors, emotional intensity, swirling patterns, impasto",
    "frida_kahlo_style": "Frida Kahlo style, surrealism, self-portraits, Mexican folk art, symbolic, vibrant colors, emotional, dreamlike",
    "j_m_w_turner_style": "J.M.W. Turner style, Romantic landscape, atmospheric, light effects, turbulent skies, sublime, dramatic",
    "john_constable_style": "John Constable style, naturalistic landscape, cloud studies, rural scenes, fresh colors, realistic light",
    "claude_monet_style": "Claude Monet style, Impressionism, light and shadow, fleeting moments, vibrant colors, water lilies, atmospheric",
    "caspar_david_friedrich_style": "Caspar David Friedrich style, Romantic landscape, contemplative, solitary figures, sublime nature, melancholic, spiritual",
    "ansel_adams_style": "Ansel Adams style, black and white photography, sharp details, grand landscapes, dramatic contrasts, majestic", # 사진이지만 스타일로서 추가
    "paul_cezanne_style": "Paul Cézanne style, Post-Impressionism, geometric forms, multiple perspectives, structured composition, still life",
    "willem_kalf_style": "Willem Kalf style, Dutch Golden Age, opulent still life, rich textures, detailed, chiaroscuro",
    "oskar_kokoschka_style": "Oskar Kokoschka style, Expressionism, intense portraits, distorted forms, psychological depth, vibrant colors",
    "jan_vermeer_style": "Jan Vermeer style, Dutch Golden Age, domestic scenes, soft light, serene, realistic, meticulous detail",
    "pieter_bruegel_style": "Pieter Bruegel the Elder style, Renaissance, peasant life, crowded scenes, moralistic, detailed landscapes",
    "edgar_degas_style": "Edgar Degas style, Impressionism, ballet dancers, candid moments, unique perspectives, pastel, movement",

    # 주요 예술 운동 및 스타일 화가
    "raphael_sanzio_style": "Raphael Sanzio style, High Renaissance, harmonious composition, graceful figures, idealized beauty, classical",
    "sandro_botticelli_style": "Sandro Botticelli style, Early Renaissance, flowing lines, delicate figures, mythological themes, vibrant colors",
    "jan_van_eyck_style": "Jan van Eyck style, Early Netherlandish, meticulous detail, rich textures, oil painting, realistic light",
    "caravaggio_style": "Caravaggio style, Baroque, dramatic chiaroscuro, intense realism, theatrical lighting, powerful figures",
    "peter_paul_rubens_style": "Peter Paul Rubens style, Baroque, dynamic composition, fleshy figures, vibrant colors, mythological scenes, energetic",
    "jean_antoine_watteau_style": "Jean-Antoine Watteau style, Rococo, delicate colors, playful scenes, elaborate ornamentation, curving lines, whimsical",
    "francois_boucher_style": "François Boucher style, Rococo, pastoral scenes, mythological, sensual, soft colors, decorative",
    "jean_honore_fragonard_style": "Jean-Honore Fragonard style, Rococo, playful, romantic, lighthearted, fluid brushwork, vibrant",
    "jean_auguste_dominique_ingres_style": "Jean-Auguste-Dominique Ingres style, Neoclassical, precise lines, smooth finish, idealized forms, academic",
    "gustave_courbet_style": "Gustave Courbet style, Realism, true-to-life depiction, unembellished reality, social commentary, gritty details",
    "edouard_manet_style": "Édouard Manet style, Realism, modern life, bold brushstrokes, flat areas of color, controversial subjects",
    "ilya_repin_style": "Ilya Repin style, Russian Realism, historical scenes, portraits, social realism, dramatic, detailed",
    "pierre_auguste_renoir_style": "Pierre-Auguste Renoir style, Impressionism, joyful scenes, soft brushstrokes, vibrant colors, figure painting",
    "camille_pissarro_style": "Camille Pissarro style, Impressionism, rural landscapes, cityscapes, gentle brushwork, light effects",
    "bert_morisot_style": "Berthe Morisot style, Impressionism, domestic scenes, portraits of women and children, light, delicate",
    "paul_gauguin_style": "Paul Gauguin style, Post-Impressionism, symbolic, bold colors, flattened forms, exotic themes, primitive art",
    "georges_seurat_style": "Georges Seurat style, Pointillism, systematic dots of color, scientific approach, serene scenes",
    "gustav_klimt_style": "Gustav Klimt style, Symbolism, Art Nouveau, golden patterns, decorative, sensual, allegorical figures",
    "gustave_moreau_style": "Gustave Moreau style, Symbolism, mythological, mystical, dreamlike, intricate details, rich colors",
    "odilon_redon_style": "Odilon Redon style, Symbolism, fantastical, dreamlike, dark, mysterious, charcoal, pastel",
    "alphonse_mucha_style": "Alphonse Mucha style, Art Nouveau, flowing lines, decorative borders, beautiful women, intricate patterns, posters",
    "ernst_ludwig_kirchner_style": "Ernst Ludwig Kirchner style, Expressionism, distorted figures, harsh colors, urban scenes, psychological tension",
    "edvard_munch_style": "Edvard Munch style, Expressionism, emotional, anxiety, psychological themes, swirling lines, dark colors",
    "wassily_kandinsky_style": "Wassily Kandinsky style, Abstract Expressionism, pure abstraction, geometric forms, spiritual, vibrant colors",
    "egon_schiele_style": "Egon Schiele style, Expressionism, raw, distorted figures, self-portraits, psychological, melancholic",
    "georges_braque_style": "Georges Braque style, Cubism, fragmented forms, geometric shapes, multiple perspectives, abstract composition, analytical, synthetic",
    "juan_gris_style": "Juan Gris style, Cubism, synthetic cubism, geometric forms, vibrant colors, collage elements",
    "umberto_boccioni_style": "Umberto Boccioni style, Futurism, dynamic motion, speed, technology, urban energy, fragmented forms, blur of movement",
    "giacomo_balla_style": "Giacomo Balla style, Futurism, light and movement, abstract patterns, vibrant colors",
    "kazimir_malevich_style": "Kazimir Malevich style, Suprematism, pure geometric forms, black square, abstract, minimalist",
    "el_lissitzky_style": "El Lissitzky style, Constructivism, geometric abstraction, propaganda art, architectural, bold forms",
    "marcel_duchamp_style": "Marcel Duchamp style, Dadaism, ready-made, conceptual art, subversive, ironic",
    "man_ray_style": "Man Ray style, Dadaism, Surrealism, photography, experimental, dreamlike, avant-garde",
    "hannah_hoch_style": "Hannah Höch style, Dadaism, photomontage, collage, social commentary, feminist",
    "salvador_dali_style": "Salvador Dalí style, Surrealism, dreamscapes, melting clocks, bizarre imagery, meticulous detail",
    "rene_magritte_style": "René Magritte style, Surrealism, thought-provoking, ordinary objects in unusual contexts, philosophical, mysterious",
    "max_ernst_style": "Max Ernst style, Surrealism, frottage, collage, dream imagery, fantastical creatures",
    "jackson_pollock_style": "Jackson Pollock style, Abstract Expressionism, drip painting, action painting, chaotic, energetic",
    "mark_rothko_style": "Mark Rothko style, Abstract Expressionism, color field painting, large rectangular blocks of color, spiritual, contemplative",
    "willem_de_kooning_style": "Willem de Kooning style, Abstract Expressionism, gestural, raw, vibrant colors, distorted figures",
    "andy_warhol_style": "Andy Warhol style, Pop Art, silkscreen, mass production, celebrity portraits, bright colors, iconic imagery, graphic, bright",
    "roy_lichtenstein_style": "Roy Lichtenstein style, Pop Art, comic book panels, Ben-Day dots, bold outlines, ironic, graphic",
    "keith_haring_style": "Keith Haring style, Pop Art, street art, bold lines, dancing figures, social commentary, vibrant colors",
    "victor_vasarely_style": "Victor Vasarely style, Op Art, geometric patterns, optical illusions, vibrating effects, visual trickery, mesmerizing",
    "bridget_riley_style": "Bridget Riley style, Op Art, black and white patterns, visual movement, rhythmic, abstract",
    "donald_judd_style": "Donald Judd style, Minimalism, geometric forms, industrial materials, repetitive structures, simple",
    "frank_stella_style": "Frank Stella style, Minimalism, geometric patterns, bold colors, non-representational",
    "joseph_kosuth_style": "Joseph Kosuth style, Conceptual Art, text-based art, philosophical, idea-driven",
    "sol_lewitt_style": "Sol LeWitt style, Conceptual Art, systematic art, geometric, instructions-based",
    "chuck_close_style": "Chuck Close style, Photorealism, hyperrealistic portraits, grid technique, large scale, detailed",
    "richard_estes_style": "Richard Estes style, Photorealism, urban landscapes, reflections, precise detail, glass, chrome",
    "ron_mueck_style": "Ron Mueck style, Hyperrealism sculpture, exaggerated scale, realistic human figures, unsettling", # 조각이지만 스타일로 추가

    # 기타 현대 및 특수 장르/분야 화가/아티스트
    "beeple_style": "Beeple style, digital art, NFT art, surreal, dystopian, futuristic, pop culture references, vibrant",
    "refik_anadol_style": "Refik Anadol style, digital art, AI art, data sculpture, immersive installations, fluid, dynamic",
    "pak_style": "Pak style, NFT art, conceptual, minimalist, blockchain art, abstract",
    "hayao_miyazaki_style": "Hayao Miyazaki style, Studio Ghibli, anime art, hand-drawn animation, soft colors, dreamy atmosphere, whimsical, lush landscapes",
    "katsuhiro_otomo_style": "Katsuhiro Otomo style, Akira, cyberpunk anime, detailed urban landscapes, gritty, dynamic action, futuristic",
    "jean_giraud_moebius_style": "Jean Giraud Moebius style, comic art, sci-fi illustration, intricate details, surreal landscapes, flowing lines, visionary",
    "kent_williams_style": "Kent Williams style, comic art, painting, expressive brushwork, dark themes, psychological, painterly",
    # [추가 부분 시작] 마블 및 디즈니 스타일 프롬프트
    "marvel_style": "Marvel comics art, superhero comic book, dynamic action pose, bold outlines, strong shading, vibrant colors, epic scene, cinematic, powerful, muscular figures",
    # [수정] Disney 스타일 프롬프트 디테일 강화
    "disney_style": "Disney animation style, classic cartoon, hand-drawn animation, whimsical, magical, expressive characters, fairytale, vibrant colors, smooth animation, clean lines, Pixar style, 3D animated movie, CGI, smooth rendering, family-friendly, charming, **soft character design, exaggerated expressions, fluid movement, round shapes, iconic character features, bright and cheerful palette, enchanting atmosphere, musical quality, heartwarming scenes, clear storytelling, traditional animation feel, magical elements, detailed backgrounds with a storybook quality**",
    # [추가 부분 시작] 동양화 스타일 프롬프트
    "korean_ink_wash_style": "Korean ink wash painting, sumukhwa, subtle ink tones, expressive brushwork, spiritual landscape, minimalist, serene, traditional Korean art",
    "korean_color_painting_style": "Korean color painting, chaesaekhwa, vibrant colors, intricate details, traditional patterns, rich pigments, decorative, folk art influence",
    "korean_literati_painting_style": "Korean literati painting, muninhwa, scholarly art, expressive ink, personal, poetic, subtle, natural themes",
    "korean_folk_painting_style": "Korean folk painting, minhwa, anonymous art, vibrant, symbolic motifs, bold colors, whimsical, protective, naive",
    "korean_buddhist_painting_style": "Korean Buddhist painting, bulhwa, religious themes, intricate details, bright colors, temple art, spiritual, ornate",
    "chinese_ink_wash_style": "Chinese ink wash painting, shan shui, literati painting, expressive brushwork, atmospheric perspective, misty mountains, flowing rivers, scholarly, traditional Chinese art",
    "chinese_gongbi_style": "Chinese Gongbi painting, meticulous detail, fine lines, vibrant colors, courtly scenes, narrative, precise, traditional Chinese court art",
    "chinese_xieyi_style": "Chinese Xieyi painting, freehand, expressive, spontaneous, bold brushstrokes, minimalist, abstract Chinese art",
    "japanese_ukiyo_e_style": "Ukiyo-e style, Japanese woodblock print, bold outlines, flat colors, everyday life scenes, kabuki actors, courtesans, landscapes, Edo period, traditional Japanese art",
    "japanese_nihonga_style": "Nihonga painting, traditional Japanese materials, mineral pigments, silk painting, delicate, refined, subtle colors, modern Japanese art",
    "japanese_sumie_style": "Japanese Sumie, ink wash painting, monochromatic, Zen aesthetic, spontaneous brushwork, minimalist, serene",
    "japanese_yamato_e_style": "Japanese Yamato-e, traditional Japanese narrative painting, illustrating literature, distinct Japanese aesthetic, vibrant colors, decorative",
    "japanese_kano_style": "Japanese Kano school, decorative, large-scale works, strong brushwork, gold leaf, influential Japanese art school",
    "japanese_rinpa_style": "Japanese Rinpa school, decorative, bold designs, natural themes, gold leaf, silver leaf, elegant, traditional Japanese art",
    # [추가 부분 시작] 동양화 화가 스타일 프롬프트
    # 한국화 화가
    "jeong_seon_style": "Jeong Seon style, Jin-gyeong Sansuhwa, real landscape, dynamic brushwork, ink wash, Korean traditional painting",
    "kim_jeong_hui_style": "Kim Jeong-hui style, Chusa, literati painting, orchid, calligraphy, scholarly, Korean traditional painting",
    "jang_seung_eop_style": "Jang Seung-eop style, Owon, diverse subjects, landscape, figure, bird-and-flower, bold brushwork, Korean traditional painting",
    "yi_am_style": "Yi Am style, animal painting, dog, meticulous detail, lively, Korean traditional painting",
    "byeon_sang_byeok_style": "Byeon Sang-byeok style, animal painting, cat, chicken, realistic, Korean traditional painting",
    "shin_saimdang_style": "Shin Saimdang style, Chochungdo, delicate, detailed, insects, plants, vibrant colors, Korean traditional painting",
    "kim_hong_do_style": "Kim Hong-do style, Danwon, genre painting, folk scenes, lively, expressive, Korean traditional painting",
    "kang_se_hwang_style": "Kang Se-hwang style, literati painting, landscape, Four Gentlemen, scholarly, Korean traditional painting",
    "yun_du_seo_style": "Yun Du-seo style, self-portrait, horse painting, genre painting, realistic, Korean traditional painting",
    # 중국화 화가
    "wang_wei_style": "Wang Wei style, Chinese literati painting, ink wash, landscape, poetic, serene, Tang Dynasty",
    "dong_yuan_style": "Dong Yuan style, Southern School painting, ink wash, soft brushwork, misty landscape, Five Dynasties",
    "juran_style": "Juran style, Southern School painting, ink wash, textured mountains, serene landscape, Five Dynasties",
    "ma_yuan_style": "Ma Yuan style, Southern Song Dynasty, 'one-corner' composition, dramatic landscape, sharp brushwork",
    "xia_gui_style": "Xia Gui style, Southern Song Dynasty, 'one-corner' composition, abbreviated brushwork, minimalist landscape",
    "huang_gongwang_style": "Huang Gongwang style, Yuan Dynasty, literati painting, dry brushwork, layered mountains, expressive",
    "ni_zan_style": "Ni Zan style, Yuan Dynasty, literati painting, sparse composition, dry brush, desolate landscape",
    "wang_meng_style": "Wang Meng style, Yuan Dynasty, literati painting, dense composition, intricate textures, layered mountains",
    "wu_zhen_style": "Wu Zhen style, Yuan Dynasty, literati painting, bamboo, ink wash, simple, elegant",
    "shi_tao_style": "Shi Tao style, Qing Dynasty, individualist, expressive brushwork, unconventional composition, free spirit",
    "bada_shanren_style": "Bada Shanren style, Qing Dynasty, minimalist, exaggerated forms, melancholic, ink wash, unique",
    "qiu_ying_style": "Qiu Ying style, Ming Dynasty, Gongbi painting, meticulous detail, vibrant colors, narrative scenes",
    "emperor_huizong_style": "Emperor Huizong of Song style, Song Dynasty, bird-and-flower painting, delicate, realistic, imperial court art",
    "liang_kai_style": "Liang Kai style, Southern Song Dynasty, Chan (Zen) painting, spontaneous brushwork, figure painting, expressive",
    "muqi_fachang_style": "Muqi Fachang style, Southern Song Dynasty, Chan (Zen) painting, ink wash, minimalist, spiritual, subtle",
    # 일본화 화가
    "katsushika_hokusai_style": "Katsushika Hokusai style, Ukiyo-e, woodblock print, dynamic composition, landscape, Great Wave, bold lines",
    "utagawa_hiroshige_style": "Utagawa Hiroshige style, Ukiyo-e, landscape, travel scenes, atmospheric effects, woodblock print",
    "toshusai_sharaku_style": "Toshusai Sharaku style, Ukiyo-e, Kabuki actor portraits, exaggerated features, dramatic, bold",
    "kitagawa_utamaro_style": "Kitagawa Utamaro style, Ukiyo-e, Bijin-ga, beautiful women, elegant, delicate, woodblock print",
    "yokoyama_taikan_style": "Yokoyama Taikan style, Nihonga, modern Japanese painting, misty landscapes, spiritual, subtle colors",
    "hishida_shunso_style": "Hishida Shunso style, Nihonga, modern Japanese painting, delicate colors, atmospheric, soft forms",
    "sesshu_toyo_style": "Sesshu Toyo style, Japanese ink wash painting, Sumi-e, bold brushwork, dynamic, minimalist landscape",
    "sen_no_rikyu_style": "Sen no Rikyu style, Japanese tea ceremony, Sumi-e, minimalist, wabi-sabi, serene",
    "kanaoka_takanobu_style": "Kanaoka Takanobu style, Yamato-e, narrative painting, vibrant colors, decorative, classical Japanese",
    "kano_eitoku_style": "Kano Eitoku style, Kano school, large scale, decorative, gold leaf, powerful, dynamic, Momoyama period",
    "kano_tanyu_style": "Kano Tan'yu style, Kano school, restrained, elegant, ink monochrome, Edo period",
    "ogata_korin_style": "Ogata Korin style, Rinpa school, decorative, bold designs, natural themes, gold leaf, silver leaf, elegant, traditional Japanese art",
    "tawaraya_sotatsu_style": "Tawaraya Sotatsu style, Rinpa school, decorative, bold designs, natural themes, ink wash, gold leaf",
    # [추가 부분 끝]
    
    # [추가 부분 시작] 이미지 원본 유지 관련 프롬프트
    "original_pose_preservation": "maintain original pose, preserve original body language, pose transfer, consistent stance, accurate posture replication, no pose distortion",
    "original_color_palette_preservation": "maintain original color palette, preserve original colors, consistent color scheme, exact color reproduction, no color shift, original hues, natural colors",
    "original_form_preservation": "maintain original form, preserve original shape, consistent silhouette, accurate object replication, no distortion of form, natural outline",
    # [새로 추가된 부분] 얼굴 특징 및 인종/민족적 특징 보존 프롬프트
    "original_facial_features_preservation": "maintain original facial features, preserve original face structure, accurate facial proportions, consistent eye shape, nose shape, mouth shape, no facial distortion, original skin tone, original hair color and style, maintain original expression, preserve original ethnic features, consistent racial characteristics, East Asian features, Korean features, Japanese features, Chinese features",
    "original_body_shape_preservation": "maintain original body shape, preserve original physique, consistent body proportions, accurate body contours, no body distortion",
    # [새로 추가된 부분] 3D 및 입체감 강화 프롬프트
    "enhanced_3d_volume": "strong volumetric presence, tangible forms, sculptural quality, deep spatial rendering, profound depth, realistic perspective, accurate foreshortening, dimensional accuracy, robust shadows, clear light and shadow interplay, sense of weight and mass, solid objects, three-dimensional space, immersive depth of field, realistic atmospheric perspective, physical dimensionality",
    "realistic_lighting_shadows": "realistic lighting, natural shadows, volumetric light, soft ambient occlusion, sharp highlights, accurate reflections, subsurface scattering, global illumination, ray tracing, realistic light physics",
    "architectural_detail": "precise architectural details, structural integrity, realistic material rendering (concrete, glass, metal), accurate building forms, urban realism, detailed infrastructure, strong sense of scale, volumetric buildings"
    # [추가 부분 끝]
}
